// This is an autogenerated header file
#ifndef PYJU_VERSION_H

#define PYJU_VERSION_H
#define PYJU_VERSION_STRING "0.1.0-dev"
#define PYJU_VERSION_MAJOR 0
#define PYJU_VERSION_MINOR 1
#define PYJU_VERSION_PATCH 0
#define PYJU_VERSION_IS_RELEASE 0

#endif
